# Powerlevel10k instant prompt
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="powerlevel10k/powerlevel10k"

# Plugins ativos (adicionei os de sugestão e cores)
plugins=(git common-aliases zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# Carregar Aliases Externos
[[ -f ~/.aliases ]] && source ~/.aliases

# Carregar Configuração do P10k
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Ajuste de PATH para ser portátil entre máquinas
export PATH="$HOME/.local/bin:$PATH"
